// ─────────────────────────────────────────────────────────────────────────────
// CONTRACT ADDRESSES  (replace with real addresses after deploy)
// ─────────────────────────────────────────────────────────────────────────────
export const ADDRESSES = {
  equestria1155:    "0x0000000000000000000000000000000000000001" as `0x${string}`,
  amm:              "0x0000000000000000000000000000000000000002" as `0x${string}`,
  governanceToken:  "0x0000000000000000000000000000000000000003" as `0x${string}`,
  myGovernor:       "0x0000000000000000000000000000000000000004" as `0x${string}`,
  nftRentalVault:   "0x0000000000000000000000000000000000000005" as `0x${string}`,
  vrfConsumer:      "0x0000000000000000000000000000000000000006" as `0x${string}`,
  gameTokenFactory: "0x0000000000000000000000000000000000000007" as `0x${string}`,
  gameToken:        "0x0000000000000000000000000000000000000008" as `0x${string}`,
  lpToken:          "0x0000000000000000000000000000000000000009" as `0x${string}`,
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// TOKEN IDs  (from Equestria1155.sol)
// ─────────────────────────────────────────────────────────────────────────────
export const TOKEN_IDS = {
  HONESTY:           1n,
  KINDNESS:          2n,
  LAUGHTER:          3n,
  GENEROSITY:        4n,
  LOYALTY:           5n,
  MAGIC:             6n,
  PINKIE_PIE:        1001n,
  STARLIGHT_GLIMMER: 1002n,
} as const;

export const ELEMENT_NAMES: Record<string, string> = {
  "1": "Honesty",
  "2": "Kindness",
  "3": "Laughter",
  "4": "Generosity",
  "5": "Loyalty",
  "6": "Magic",
  "1001": "Pinkie Pie",
  "1002": "Starlight Glimmer",
};

export const PONY_RECIPES: Record<string, Record<string, number>> = {
  "1001": { "1": 15, "2": 10, "3": 100, "4": 20, "5": 5,  "6": 0  },
  "1002": { "1": 5,  "2": 3,  "3": 0,   "4": 0,  "5": 15, "6": 80 },
};

// ─────────────────────────────────────────────────────────────────────────────
// ABIs
// ─────────────────────────────────────────────────────────────────────────────

export const EQUESTRIA_1155_ABI = [
  // read
  { name: "balanceOf",        type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "id", type: "uint256" }],
    outputs: [{ type: "uint256" }] },
  { name: "balanceOfBatch",   type: "function", stateMutability: "view",
    inputs: [{ name: "owners", type: "address[]" }, { name: "ids", type: "uint256[]" }],
    outputs: [{ type: "uint256[]" }] },
  { name: "isApprovedForAll", type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "operator", type: "address" }],
    outputs: [{ type: "bool" }] },
  { name: "contractOwner",    type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "address" }] },
  // write
  { name: "craft",            type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "ponyId", type: "uint256" }], outputs: [] },
  { name: "mint",             type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "to", type: "address" }, { name: "id", type: "uint256" },
             { name: "value", type: "uint256" }, { name: "data", type: "bytes" }],
    outputs: [] },
  { name: "setApprovalForAll", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "operator", type: "address" }, { name: "approved", type: "bool" }],
    outputs: [] },
  { name: "safeTransferFrom", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" },
             { name: "id", type: "uint256" }, { name: "value", type: "uint256" },
             { name: "data", type: "bytes" }], outputs: [] },
  // events
  { name: "TransferSingle",   type: "event",
    inputs: [{ name: "_operator", type: "address", indexed: true },
             { name: "_from",     type: "address", indexed: true },
             { name: "_to",       type: "address", indexed: true },
             { name: "_id",       type: "uint256", indexed: false },
             { name: "_value",    type: "uint256", indexed: false }] },
] as const;

export const AMM_ABI = [
  // read
  { name: "tokenA",       type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "tokenB",       type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "reserveA",     type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "reserveB",     type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "quoteAForB",   type: "function", stateMutability: "view",
    inputs: [{ name: "amountIn", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "quoteBForA",   type: "function", stateMutability: "view",
    inputs: [{ name: "amountIn", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "getAmountOut", type: "function", stateMutability: "pure",
    inputs: [{ name: "amountIn", type: "uint256" }, { name: "reserveIn", type: "uint256" },
             { name: "reserveOut", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "lpToken",      type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  // write
  { name: "swap",           type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "tokenIn", type: "address" }, { name: "amountIn", type: "uint256" },
             { name: "minAmountOut", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "addLiquidity",   type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "amountADesired", type: "uint256" }, { name: "amountBDesired", type: "uint256" },
             { name: "minAmountA", type: "uint256" }, { name: "minAmountB", type: "uint256" }],
    outputs: [{ name: "amountA", type: "uint256" }, { name: "amountB", type: "uint256" },
              { name: "liquidity", type: "uint256" }] },
  { name: "removeLiquidity", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "lpAmount", type: "uint256" }, { name: "minAmountA", type: "uint256" },
             { name: "minAmountB", type: "uint256" }],
    outputs: [{ name: "amountA", type: "uint256" }, { name: "amountB", type: "uint256" }] },
  // events
  { name: "Swap", type: "event",
    inputs: [{ name: "trader",   type: "address", indexed: true },
             { name: "tokenIn",  type: "address", indexed: true },
             { name: "tokenOut", type: "address", indexed: true },
             { name: "amountIn", type: "uint256", indexed: false },
             { name: "amountOut",type: "uint256", indexed: false }] },
  { name: "LiquidityAdded", type: "event",
    inputs: [{ name: "provider",      type: "address", indexed: true },
             { name: "amountA",       type: "uint256", indexed: false },
             { name: "amountB",       type: "uint256", indexed: false },
             { name: "lpTokensMinted",type: "uint256", indexed: false }] },
] as const;

export const GOVERNANCE_TOKEN_ABI = [
  { name: "balanceOf",        type: "function", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "totalSupply",      type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "allowance",        type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }] },
  { name: "getVotes",         type: "function", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "delegates",        type: "function", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "address" }] },
  { name: "approve",          type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
  { name: "delegate",         type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "delegatee", type: "address" }], outputs: [] },
  { name: "transfer",         type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
  { name: "name",   type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { name: "symbol", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
] as const;

export const GOVERNOR_ABI = [
  // read
  { name: "name",              type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { name: "proposalCount",     type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "votingDelay",       type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "votingPeriod",      type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "quorum",            type: "function", stateMutability: "view",
    inputs: [{ name: "blockNumber", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "proposalThreshold", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "state",             type: "function", stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ type: "uint8" }] },
  { name: "hasVoted",          type: "function", stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }, { name: "account", type: "address" }],
    outputs: [{ type: "bool" }] },
  { name: "proposalVotes",     type: "function", stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [{ name: "againstVotes", type: "uint256" },
              { name: "forVotes",     type: "uint256" },
              { name: "abstainVotes", type: "uint256" }] },
  { name: "proposalDeadline",  type: "function", stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "proposalSnapshot",  type: "function", stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  // write
  { name: "propose",    type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "targets",      type: "address[]" },
             { name: "values",       type: "uint256[]" },
             { name: "calldatas",    type: "bytes[]" },
             { name: "description",  type: "string" }],
    outputs: [{ type: "uint256" }] },
  { name: "castVote",   type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }, { name: "support", type: "uint8" }],
    outputs: [{ type: "uint256" }] },
  { name: "queue",      type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "targets", type: "address[]" }, { name: "values", type: "uint256[]" },
             { name: "calldatas", type: "bytes[]" }, { name: "descriptionHash", type: "bytes32" }],
    outputs: [{ type: "uint256" }] },
  { name: "execute",    type: "function", stateMutability: "payable",
    inputs: [{ name: "targets", type: "address[]" }, { name: "values", type: "uint256[]" },
             { name: "calldatas", type: "bytes[]" }, { name: "descriptionHash", type: "bytes32" }],
    outputs: [{ type: "uint256" }] },
  // events
  { name: "ProposalCreated", type: "event",
    inputs: [{ name: "proposalId",  type: "uint256", indexed: false },
             { name: "proposer",    type: "address",  indexed: false },
             { name: "targets",     type: "address[]",indexed: false },
             { name: "values",      type: "uint256[]",indexed: false },
             { name: "signatures",  type: "string[]", indexed: false },
             { name: "calldatas",   type: "bytes[]",  indexed: false },
             { name: "voteStart",   type: "uint256",  indexed: false },
             { name: "voteEnd",     type: "uint256",  indexed: false },
             { name: "description", type: "string",   indexed: false }] },
  { name: "VoteCast", type: "event",
    inputs: [{ name: "voter",      type: "address", indexed: true },
             { name: "proposalId", type: "uint256", indexed: false },
             { name: "support",    type: "uint8",   indexed: false },
             { name: "weight",     type: "uint256", indexed: false },
             { name: "reason",     type: "string",  indexed: false }] },
] as const;

export const NFT_RENTAL_VAULT_ABI = [
  // read
  { name: "asset",         type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { name: "totalAssets",   type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "balanceOf",     type: "function", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "totalSupply",   type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "convertToShares",  type: "function", stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "convertToAssets",  type: "function", stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "previewDeposit",   type: "function", stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { name: "isRenting",     type: "function", stateMutability: "view",
    inputs: [{ name: "", type: "address" }], outputs: [{ type: "bool" }] },
  { name: "boostBps",      type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "boostedNftId",  type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { name: "rentals",       type: "function", stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "renter", type: "address" }, { name: "stakedAt", type: "uint256" }] },
  { name: "name",   type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { name: "symbol", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  // write
  { name: "deposit",    type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }],
    outputs: [{ type: "uint256" }] },
  { name: "withdraw",   type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" },
             { name: "owner", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "redeem",     type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "shares", type: "uint256" }, { name: "receiver", type: "address" },
             { name: "owner", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "stakeNFT",   type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "nftId", type: "uint256" }], outputs: [] },
  { name: "unstakeNFT", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "nftId", type: "uint256" }], outputs: [] },
  // events
  { name: "NFTStaked",    type: "event",
    inputs: [{ name: "renter", type: "address", indexed: true },
             { name: "nftId",  type: "uint256", indexed: false }] },
  { name: "NFTUnstaked",  type: "event",
    inputs: [{ name: "renter", type: "address", indexed: true },
             { name: "nftId",  type: "uint256", indexed: false }] },
  { name: "YieldInjected", type: "event",
    inputs: [{ name: "amount", type: "uint256", indexed: false }] },
  { name: "Deposit", type: "event",
    inputs: [{ name: "sender",   type: "address", indexed: true },
             { name: "owner",    type: "address", indexed: true },
             { name: "assets",   type: "uint256", indexed: false },
             { name: "shares",   type: "uint256", indexed: false }] },
] as const;

export const VRF_CONSUMER_ABI = [
  { name: "lastRandomResult",  type: "function", stateMutability: "view",
    inputs: [{ name: "", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "requestToSender",   type: "function", stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }], outputs: [{ type: "address" }] },
  { name: "requestRandom",     type: "function", stateMutability: "nonpayable",
    inputs: [], outputs: [{ name: "requestId", type: "uint256" }] },
  { name: "RandomRequested",   type: "event",
    inputs: [{ name: "requestId", type: "uint256", indexed: true },
             { name: "sender",    type: "address",  indexed: true }] },
  { name: "RandomFulfilled",   type: "event",
    inputs: [{ name: "requestId",  type: "uint256", indexed: true },
             { name: "randomWord", type: "uint256",  indexed: false }] },
] as const;

export const GAME_TOKEN_FACTORY_ABI = [
  { name: "allTokensLength", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "allTokens",       type: "function", stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }], outputs: [{ type: "address" }] },
  { name: "predictAddress",  type: "function", stateMutability: "view",
    inputs: [{ name: "name", type: "string" }, { name: "symbol", type: "string" },
             { name: "salt", type: "bytes32" }], outputs: [{ type: "address" }] },
  { name: "createToken",    type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "name", type: "string" }, { name: "symbol", type: "string" }],
    outputs: [{ name: "token", type: "address" }] },
  { name: "createToken2",   type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "name", type: "string" }, { name: "symbol", type: "string" },
             { name: "salt", type: "bytes32" }],
    outputs: [{ name: "token", type: "address" }] },
  { name: "TokenCreated",   type: "event",
    inputs: [{ name: "token",   type: "address", indexed: true },
             { name: "salt",    type: "bytes32",  indexed: true },
             { name: "create2", type: "bool",     indexed: false }] },
] as const;

export const ERC20_ABI = [
  { name: "balanceOf",  type: "function", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { name: "allowance",  type: "function", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }] },
  { name: "approve",    type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
  { name: "totalSupply",type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { name: "symbol",     type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "string" }] },
  { name: "decimals",   type: "function", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint8" }] },
] as const;
