[profile.default]
src    = "src"
test   = "test"
script = "script"
out    = "out"
libs   = ["lib"]

optimizer = true
optimizer_runs = 20

ignored_error_codes = [
    5667
]
ignored_warnings_from = ["lib/"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[lint]
exclude_lints = [
    "screaming-snake-case-immutable",
    "mixed-case-variable",
    "mixed-case-function",
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/lQnUnkuzwvejj3sFHfYJ5"
